--- EmmyLua intellisense stub for the Transform userdata type.
--- Hand-written -- NOT regenerated by Scripts/codegen.py (unlike lua_stubs.lua,
--- which is overwritten wholesale on every codegen run). Transform is a full
--- Lua userdata (Source/Scripting/LuaTransform.cpp), not a codegen'd REF
--- struct/class, so it has no auto-generated stub. Keep this in sync by hand
--- if LuaTransform.cpp's method/constructor list changes.
---
--- Filename must end in "lua_stubs.lua" -- ScriptManager::reload_all_scripts
--- skips any script path containing that substring, so this file (like the
--- generated one) is never executed at runtime, only read by the language server.
---@diagnostic disable

---@class Transform : userdata
Transform = {}

---@return Transform
function Transform.new() end

---@return Transform
function Transform.identity() end

---@param pos lVec3
---@return Transform
function Transform.from_pos(pos) end

---@param pos lVec3
---@param rot lQuat
---@return Transform
function Transform.from_pos_rot(pos, rot) end

---@param pos lVec3
---@param rot lQuat
---@param scale lVec3
---@return Transform
function Transform.from_pos_rot_scale(pos, rot, scale) end

---@param eye lVec3
---@param target lVec3
---@param up lVec3
---@return Transform
function Transform.look_at(eye, target, up) end

---@return Transform
function Transform:inverse() end

---@return lVec3
function Transform:translation() end

---@return lQuat
function Transform:rotation() end

---@return lVec3
function Transform:scale() end

---@return lVec3, lQuat, lVec3
function Transform:decompose() end

---@param pos lVec3
---@return Transform
function Transform:set_translation(pos) end

---@param p lVec3
---@return lVec3
function Transform:transform_point(p) end

---@param v lVec3
---@return lVec3
function Transform:transform_direction(v) end

--- Same as the `*` operator; Transform * Transform composes, Transform * {x,y,z} transforms a point.
---@param other Transform
---@return Transform
function Transform:mul(other) end
