--- EmmyLua intellisense stub for the Vec3/Quat metatables attached to lVec3/lQuat tables.
--- Hand-written -- NOT regenerated by Scripts/codegen.py (unlike lua_stubs.lua,
--- which is overwritten wholesale on every codegen run). lVec3/lQuat are still
--- codegen'd REF structs that cross as plain {x,y,z}/{w,x,y,z} tables (see
--- lua_stubs.lua for their field-only ---@class), but Source/Scripting/LuaVecQuat.cpp
--- attaches a metatable to those tables giving them operators and methods; this
--- file documents that extra surface. Keep in sync by hand if LuaVecQuat.cpp's
--- method/constructor list changes.
---
--- Filename must end in "lua_stubs.lua" -- ScriptManager::reload_all_scripts
--- skips any script path containing that substring, so this file (like the
--- generated one) is never executed at runtime, only read by the language server.
---@diagnostic disable

---@class Vec3 : lVec3
Vec3 = {}

---@param x number?
---@param y number?
---@param z number?
---@return Vec3
function Vec3.new(x, y, z) end

---@return number
function Vec3:length() end

---@return Vec3
function Vec3:normalize() end

---@param other lVec3
---@return number
function Vec3:dot(other) end

---@param other lVec3
---@return Vec3
function Vec3:cross(other) end

--- Same as the `+` operator.
---@param other Vec3
---@return Vec3
function Vec3.__add(self, other) end

--- Same as the `-` operator.
---@param other lVec3
---@return Vec3
function Vec3.__sub(self, other) end

--- Same as the `*` operator; Vec3 * Vec3 is component-wise, Vec3 * number scales.
---@param other lVec3|number
---@return Vec3
function Vec3.__mul(self, other) end

---@class Quat : lQuat
Quat = {}

---@param w number?
---@param x number?
---@param y number?
---@param z number?
---@return Quat
function Quat.new(w, x, y, z) end

---@return Quat
function Quat.identity() end

---@return Quat
function Quat:inverse() end

---@return Vec3
function Quat:to_euler() end

--- Same as the `*` operator; Quat * Quat composes, Quat * {x,y,z} rotates a point.
---@param other lQuat|lVec3
---@return Quat|Vec3
function Quat.__mul(self, other) end
