#pragma once
#include "GameEnginePublic.h"
#include "glm/glm.hpp"
#include "Framework/MulticastDelegate.h"
#include "IInputReciever.h"
#include "UI/GUISystemPublic.h"
#include "Game/EntityPtr.h"
#include "Render/RenderObj.h"
#include "Render/DrawPublic.h"
#include "imgui.h" 
#include "ImGuizmo.h"
#include <glm/glm.hpp>
#include "Framework/MathLib.h"
#include "Framework/Rect2d.h"
#include "Render/ViewSetup.h"
#include "OrthoCamera.h"
#include "User_Camera.h"
class EditorDoc;
class IPropertyEditor;
#include <unordered_set>
#include "Framework/MapUtil.h"
#include <unordered_map>
#include "Game/Entity.h"
#include "Game/EntityComponent.h"
#include "Framework/FnFactory.h"
#include <string>
using std::string;
#include "Level.h"